language: node_js
os:
- linux
- osx
node_js:
- '8'
install:
- travis_retry npm install -g esy@0.2.9
- esy install
script:
- esy build
- esy x cmake --version
cache:
  timeout: 360
  directories:
  - "$HOME/.esy/"
